baseURL: ""
title: "IDEA Lab"
theme: hugo-PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  defaultTheme: auto

menu:
  main:
    - name: Research
      url: /research/
      weight: 1

    - name: Team
      url: /team/
      weight: 2
