baseURL: ""
title: "IDEA Lab"

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

params:
  defaultTheme: light

menu:
  main:
    - name: Research
      url: /research/
    - name: Team
      url: /team/
